diccionario={}
nombre=input('Introduzca su nombre:')
diccionario.update({'nombre':nombre})
print(diccionario)
sexo=input('Introduzca su sexo:')
diccionario.update({'sexo':sexo})
print(diccionario)
edad=input('Introduzca su edad:')
diccionario.update({'edad':edad})
print(diccionario)
calle=input('Introduzca su calle:')
diccionario.update({'calle':calle})
print(diccionario)
telefono=input('Introduzca su numero de telefono:')
diccionario.update({'telefono':telefono})
print(diccionario)
correo=input('introduzca su correo:')
diccionario.update({'correo':correo})
print(diccionario)